# Generated by Django 4.2 on 2026-03-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254, verbose_name='Отправитель')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Получатель')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Текст письма')),
                ('folder', models.CharField(choices=[('inbox', 'Входящие'), ('sent', 'Исходящие'), ('trash', 'Корзина'), ('archive', 'Архив')], default='inbox', max_length=20, verbose_name='Папка')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['-created_at'],
            },
        ),
    ]
